### PR TITLE
tree shaking highlightjs dependency

### PR DESCRIPTION
**Pull request by stackoverfloweth**
PR Checklist:

- [x] add a short description of what's changed to the top of the `CHANGELOG.md`
- [ ] add/update tests (or don't, for reasons explained below)

## Describe this PR
This package's use of Highlight.js was over double the size of the next biggest dependency. Removing this dependency and the 3 lines from markdownParser I was able to bring down the highlightjs bundle size from 1.3M to 77.5K! 

While at first glance, I expected this to have an impact on user experience, I cannot find an instance where this change actually effected what the user sees. I confirmed the "describe" component used in a flow's readme, as well as the artifacts tab of a flow-run. Markdown entry and parsing seems uneffected by this change.

### CODE REVIEW

**Review by zhen0 — DISMISSED** [review]
This looks good to me @stackoverfloweth.  I also checked tutorials as I believe they also use markdown and looked fine.  As she did some work of the initial work on the markdown parser I'd like to have @ThatGalNatalie take a look at this before we merge.

**Review by zhen0 — CHANGES_REQUESTED** [review]
Oh actually I do have a requested change @stackoverfloweth - can you update the changelog please?  (And update to latest master!). Thanks!

**Review by ThatGalNatalie — DISMISSED** [review]
looks good to me too

**Review by zhen0 — APPROVED** [review]
Also looks good to me @stackoverfloweth - but can you add the latest from master so we can merge.

**Review by znicholasbrown — APPROVED** [review]

**Pull request merged**
