### PR TITLE
Add task run name to global search

### PR DESCRIPTION
**Pull request by madkinsz**
PR Checklist:

- [x] add a short description of what's changed to the top of the `CHANGELOG.md`
- ~[ ] add/update tests (or don't, for reasons explained below)~

## Describe this PR

Adds task run name to search

Tested in cloud-dev.
Requires https://github.com/PrefectHQ/server/pull/149 and https://github.com/PrefectHQ/cloud/pull/2884
Prod tracking card at https://github.com/PrefectHQ/cloud/projects/2#card-50500413 

Screen Shot 2020-12-02 at 2 15 06 PM

### CODE REVIEW

**Comment by znicholasbrown** [comment]
Since this requires db updates we'll hold off on merging/approving but this LGTM @madkinsz.

**Review by cicdw — APPROVED** [review]
The backend changes are officially live ✅

**Comment by znicholasbrown** [comment]
If you can move the changelog entry to the `Unreleased` feature and improvements section, I can merge this @madkinsz 👍

**Comment by madkinsz** [comment]
@znicholasbrown  done :)

**Review by znicholasbrown — APPROVED** [review]
Thanks @madkinsz !

**Pull request merged**
