### PR TITLE
404 TLC

### PR DESCRIPTION
**Pull request by zhen0**
PR Checklist:

- [x] add a short description of what's changed to the top of the `CHANGELOG.md`
- [x] add/update tests (or don't, for reasons explained below)

## Describe this PR

- Neatens the 404 page to remove the navbar (which was showing as white on smaller screens) and the footer (which should have been hidden but the route name was added incorrectly). 
- Also better handles invalid flow ids and redirects to the 404 page

### CODE REVIEW

**Comment by zhen0** [comment]
Screen Shot 2021-01-21 at 12 02 11 PM
Screen Shot 2021-01-21 at 12 00 43 PM
Screen Shot 2021-01-21 at 10 08 47 AM

**Comment by zhen0** [comment]
Old on smaller screen: Screen Shot 2021-01-21 at 12 02 11 PM

**Comment by zhen0** [comment]
Updated: 
Screen Shot 2021-01-21 at 12 05 49 PM

**Review by whimsicallyson — DISMISSED** [review]
lgtm!

**Comment by ThatGalNatalie** [comment]
I noticed that if I'm around the mobile breakpoint, the global search appears and the page becomes scrollable.  Other than that, lgtm!

https://user-images.githubusercontent.com/40726391/105404727-26b28380-5bdf-11eb-84a8-5a21b2edc141.mov

**Comment by zhen0** [comment]
I think I've removed that magnifying glass @ThatGalNatalie and I can't repro the scrolling - want to take another look?

**Comment by ThatGalNatalie** [comment]
@zhen0 I don't see that magnifying glass anymore and I can't repro the scrolling so it looks good to me!

**Review by znicholasbrown — APPROVED** [review]

**Pull request merged**
