### PR TITLE
Fix routing from invitation

### PR DESCRIPTION
**Pull request by znicholasbrown**
PR Checklist:

- [x] add a short description of what's changed to the top of the `CHANGELOG.md`
- [x] add/update tests (or don't, for reasons explained below)

## Describe this PR
This PR addresses the following:
- Membership and invitation tables not updating
- Teams not updating after accepting an invitation (Resolves: #860)
- Access denied when the IDP client application throws
- `null` tenant id on the login token, defaults to the first tenant now and throws access denied if no tenants exist

### CODE REVIEW

**Review by zhen0 — CHANGES_REQUESTED** [review]
This all looked good to me until I tried it out.  I removed my email from an old tenant and then invited that user to join.  The invitation got sent ok and I got taken to the login and then the correct page with the invitation.  However, when I clicked join I got the dreaded "cannot read property 'data' of undefined'.  Clicking on 'Back to the Dashboard' worked but I still hadn't joined my new tenant.  Clicking on the tenant switcher left me in spinning/loading limbo.  I dug around a little and the issue seems to come from the accept-membership-invitation mutation which is not returning anything.  That mutation worked fine in the IAPI.  Happy to screen-share give more details if needed.  May not be directly related to your PR but I think it's connected to the issue you're fixing.

**Comment by zhen0** [comment]
We discussed and tried to replicate but can't. Happy to approve this PR as doubt it's directly related and keep investigating separately.

**Comment by znicholasbrown** [comment]
👍🏻  Fixed some issues routing to the invitation acceptance page on application start and some small visual stuff on that page so should be good to go now.

**Comment by zhen0** [comment]
I'm seeing a flicker when i delete a user on this branch.  They are removed, come back and then are finally fully removed.

**Comment by znicholasbrown** [comment]
Ok that should be fixed now @zhen0  - looks like the `no-cache` policy wasn't being respected properly, so switched it to `network-only`.

**Comment by zhen0** [comment]
Thanks for the switch @znicholasbrown LGTM!

**Review by zhen0 — APPROVED** [review]

**Pull request merged**
