### PR TITLE
Fix auth loop

### PR DESCRIPTION
**Pull request by znicholasbrown**
PR Checklist:

- [ ] add a short description of what's changed to the top of the `CHANGELOG.md`
- [ ] add/update tests (or don't, for reasons explained below)

## Describe this PR
Looks to fix intermittent auth loops by removing auth and tenant nav guards and instead providing a `setup` method that runs before application rendering and performs auth, fetches tenants, and sets the current tenant.

### CODE REVIEW

**Review by whimsicallyson — APPROVED** [review]
code looks good! so does testing!

**Comment by wrightjonathan** [comment]
I haven't looked into the details yet, but the latest UI release which I believe only includes changes from this ticket has prevented our users accessing an instance of Prefect Server hosted on our infrastructure. I've rolled back to image ui:2021-04-15, which we were previously using, and it is working again. It could be that it is entirely related to our configuration, but I wanted to report it in case it affects anyone else or someone immediately knows what our issue might be.

Here's what was happening. Very soon after the UI starts to load in the browser we were being redirected to: https://universal.prefect.io/oauth2/  ... omitted rest of the url ...
Showing this message.
Screenshot 2021-04-22 at 11 30 00
In our case 'redirect_uri' is set to the domain name of our Prefect server.

**Comment by madkinsz** [comment]
Hey @wrightjonathan I think this is being addressed at #788

**Comment by imranq2** [comment]
We're seeing the exact same error after upgrading to 2021-04-22

**Pull request merged**
