### PR TITLE
add run config tab in flow run details

### PR DESCRIPTION
**Pull request by gmaliar**
PR Checklist:

- [x] add a short description of what's changed to the top of the `CHANGELOG.md`
- [x] add/update tests (or don't, for reasons explained below)

## Describe this PR
We're using a machine learning flow with multiple run configuration environment and image settings so it's hard for us to debug which image / env variables we ran in each run right now as we don't have visual access to the `RunConfig` object

### CODE REVIEW

**Comment by znicholasbrown** [comment]
@gmaliar thanks for the PR! It looks like you'll need to add `|| hasRunConfig` to line 91 of the flow run page details tile or this will only show up when a run also has parameters/context

**Comment by gmaliar** [comment]
Ooh good catch, I didn't notice that! 🙇 
Fixed!

**Review by znicholasbrown — APPROVED** [review]
This LGTM @gmaliar, thanks!!

**Comment by gmaliar** [comment]
🙏

**Pull request merged**
