### PR TITLE
licensing and permissions

### PR DESCRIPTION
**Pull request by ThatGalNatalie**
PR Checklist:

- [x] add a short description of what's changed to the top of the `CHANGELOG.md`
- [x] add/update tests (or don't, for reasons explained below)

## Describe this PR
This will add three new getters to the license store:
planType 
hasPermissions 
allowedUsers 

#718

### CODE REVIEW

**Review by znicholasbrown — CHANGES_REQUESTED** [review]
The permissions section of this is looking good but I'd like to remove the need for a specific plan name from the components; it'd be great if components could pass `FREE`, `STARTER`, `STANDARD`, and `ENTERPRISE` without the need for the year; this will let us change plans centrally instead of in every component.

**Comment by zhen0** [comment]
I agree with Nicholas's comment @ThatGalNatalie - adding a check in the store which can tell is a license type is free, standard or starter, irrespective of the year (or any other details that might get added) will help cut down the amount of code we need to update in future.

**Review by zhen0 — DISMISSED** [review]
Thanks for the changes @ThatGalNatalie - this looks good to me. Can you remove the package-lock.json change though?

**Review by zhen0 — DISMISSED** [review]
Thanks @ThatGalNatalie LGTM!

**Review by znicholasbrown — APPROVED** [review]

**Pull request merged**
