### PR TITLE
Remove references to certain task attributes

### PR DESCRIPTION
**Pull request by cicdw**
PR Checklist:

- [x] add a short description of what's changed to the top of the `CHANGELOG.md`
- [x] add/update tests (or don't, for reasons explained below)

## Describe this PR
This PR seeks to remove references to the following attributes of _tasks_:
- `is_terminal_task`
- `is_root_task`
- `is_reference_task`
- `mapped`

As far as I can tell, the first 3 attributes are not used anywhere within the application; however, `mapped` is definitely used and even displayed in some places.  I tried to remove all references / logic that relied on this but it's possible I forgot something.

The reason for the removal is that I'm trying to streamline some backend logic and removing these would greatly simplify those efforts.

### CODE REVIEW

**Comment by kingsleyb** [comment]
I tested a flow with a mapped task verifying activity screen, schematics, mapped run page, the card details of a task and it looks good to me.

**Review by znicholasbrown — APPROVED** [review]
LGTM @cicdw 👍🏻

**Comment by zhen0** [comment]
@cicdw - looks like this has been approved but not merged yet.  Can you update to the latest version of the master branch and then we can get it re-approved and merged.

**Comment by cicdw** [comment]
@zhen0 should be good to go

**Review by zhen0 — APPROVED** [review]
Thanks for the changes @cicdw

**Pull request merged**
