### PR TITLE
Automations update

### LINKED ISSUE #700: Add an MSTeams and a Webhook Action to Automations
**Why**

The backend allows users to create an MSTeams notification action and a general webhook action when using hooks/automations.  We could add that to the UI Automations page in the same as slack etc. 
**What**

* [ ] A user can select MSTeams as one of the action types when creating a new action in a new automation
* [ ] The user can enter the required config (secret name)

**Notes**

This should follow a similar set-up to the slack action already in automations.  

Check in with @madkinsz if you need details of the mutation and config.

### LINKED ISSUE #757: Creating a new agent config should select it during automation creation
**Why**

Creating a new agent config in the automations screen does not select it as the config you're using for that automation. I cannot think of a case where this should not be the default.

**What**

* [ ] Auto-update the selected config to the new config on creation

### LINKED ISSUE #831: Automations: Show which options are available as message template variables for actions
**Why**

Right now the automation action message box has placeholder text with templated variables, but doesn't show which variables are available for users to create their own.

**What**

* [ ] a user can see the available variables for creating their own action message templates

**Notes**

### PR DESCRIPTION
**Pull request by zhen0**
PR Checklist:

- [ ] add a short description of what's changed to the top of the `CHANGELOG.md`
- [ ] add/update tests (or don't, for reasons explained below)

## Describe this PR
- Adds a pause schedule system action 
- Adds a webhook action with JSON edit
- Closes #700 
- Closes #757 
- Closes #831

### CODE REVIEW

**Comment by madkinsz** [comment]
@znicholasbrown I'd love to be able to preview this :)

**Comment by znicholasbrown** [comment]
Preview should be working 👍

**Comment by zhen0** [comment]
Putting this in pause as changes in https://github.com/PrefectHQ/cloud/pull/3399 will mean we can remove the need to add the flow_group_id, which would simplify the code and allow us to set the pause_schedule_action to multiple flows.

**Comment by znicholasbrown** [comment]
This is working but I wonder if we should pre-populate the JSON field for the webhook payload with some example payload, and show any variables that can be included (and how to include them)

**Comment by zhen0** [comment]
I've added placeholder text for the webhook JSON.  Instead of adding more to the UI - draft docs in https://github.com/PrefectHQ/prefect/pull/4553 on how to customize an action message.

**Comment by madkinsz** [comment]
Is this waiting on something? https://github.com/PrefectHQ/prefect/pull/4553 is merged now and will be live Tuesday after I release

**Comment by zhen0** [comment]
> Is this waiting on something? [PrefectHQ/prefect#4553](https://github.com/PrefectHQ/prefect/pull/4553) is merged now and will be live Tuesday after I release

Sorry - It's been back and forth between Nicholas and I.  @znicholasbrown - ready for another review.

**Review by znicholasbrown — APPROVED** [review]
LGTM @zhen0 - thanks for the changes.

**Pull request merged**
