### PR TITLE
November Package updates

### PR DESCRIPTION
**Pull request by znicholasbrown**
November package updates

<details>
<summary>Resolutions:</summary>
<p>
Closes: #406 

Closes: #404 

Closes: #392 

Closes: #393 

Closes: #343 

Closes: #342 

Closes: #339 

Closes: #337

Closes: #336 

</p>
</details>

No significant changes here, mostly minor version bumps and some Vuetify bugfixes.

### CODE REVIEW

**Comment by znicholasbrown** [comment]
Oops, this _doesn't_ close #357 because that's a dependency of `vue-cli-plugin-apollo`; we'd need to add the `object-path` dependency explicitly or have the Vue core team cut another version with the dependency. However, it looks like this doesn't matter much to us since it's in a dependency of `graphql` that we don't use explicitly. Will leave that open for now.

**Review by zhen0 — COMMENTED** [review]
Looks fine to me @znicholasbrown (tested in netlify and local) but there's a conflict that needs resolving before we can merge.

**Comment by znicholasbrown** [comment]
That should be fixed now @zhen0, sorry about that!

**Review by zhen0 — APPROVED** [review]
Thanks @znicholasbrown LGTM!

**Pull request merged**
