### PR TITLE
update no agents warning 

### LINKED ISSUE #215: Make it more obvious that a user needs to start an agent
Currently, if a user has no agents, they see:
image

Since this is the common starting point for new users, there's an opportunity to make this more informative and helpful. For example, telling a user that they must start an agent to do work (a common misunderstanding for users that don't read the docs), or jumping-off to actions like creating a new agent config (thanks to the new persistence work by @joshmeek and @cicdw). As is, new users may not realize that this is actually a blocking problem for getting work done (if only due to its yellow color)

In addition, if there is late work AND no agents, that could be surfaced more obviously/visibily than if there's no work and no agents.

### PR DESCRIPTION
**Pull request by zhen0**
PR Checklist:

- [x] add a short description of what's changed to the top of the `CHANGELOG.md`
- [x] add/update tests (or don't, for reasons explained below)

## Describe this PR
- Changes the no agents tile color from 'warning' orange to 'error' red and updates the messages to say flows will not run without agents.  
- Also adds a link to the agents docs. 
- Together with the work on flow affinity labels, I think this closes #215

### CODE REVIEW

**Comment by madkinsz** [comment]
I noticed the first link creates a new tab but the other two navigate within the same tab--this makes some sense since the second two are within the same app but may be worth creating a new tab for all 3 anyway.

This may be a useful message to display if all of your agents are not running as well? I only had one, failed agent and a pointer to the agent docs would have been helpful yet.

**Comment by zhen0** [comment]
> I noticed the first link creates a new tab but the other two navigate within the same tab--this makes some sense since the second two are within the same app but may be worth creating a new tab for all 3 anyway.
> 
> This may be a useful message to display if all of your agents are not running as well? I only had one, failed agent and a pointer to the agent docs would have been helpful yet.

I only added one link here?

Good point on displaying the link to the docs for any error - I've added that.

**Comment by znicholasbrown** [comment]
Screen Shot 2020-10-29 at 11 35 30 AM
This looks pretty out of place as-is, could we move it to be a continuation of the line above?

**Comment by madkinsz** [comment]
> > I noticed the first link creates a new tab but the other two navigate within the same tab--this makes some sense since the second two are within the same app but may be worth creating a new tab for all 3 anyway.
> > This may be a useful message to display if all of your agents are not running as well? I only had one, failed agent and a pointer to the agent docs would have been helpful yet.
> 
> I only added one link here?

Oops sorry! I should have taken a look at the code. I was looking at 

Screen Shot 2020-10-29 at 11 04 22 AM

**Comment by zhen0** [comment]
Screen Shot 2020-10-29 at 12 18 15 PM
 
Adding as a continuation of the line above created a big-ish text block that I find harder to read/parse.  As a compromise I've added as part of the list item so it's in-line but a separate paragraph.

**Review by znicholasbrown — APPROVED** [review]
LGTM 👍

**Pull request merged**
